apiVersion: v1
kind: Namespace
metadata:
  name: hungdn
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-nginx-pod
  namespace: hungdn
data:
  index.html: |
    <h1> Hello World </h1>
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hungdn
  name: config-nginx-deploy
data:
  index.html: |
    <h1> Hello World - Deployment </h1>
