apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: hungdn
spec:
  containers:
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - mountPath: /usr/share/nginx/html # mount content of the configmap to container
          name: config
          readOnly: true
  volumes:
    - name: config # volume use configmap as content
      configMap:
        name: config-nginx-pod # configmap name
