apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: hungdn
  name: example-pv-volume
  labels:
    app: sample-app
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: Service
metadata:
  namespace: hungdn
  name: nginx
  labels:
    app: sample-app
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sample-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: hungdn
  name: sample-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app  
  serviceName: nginx
  template:
    metadata:
      labels:
        app: sample-app  
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80
          volumeMounts:
          - name: example-pvc-volume
            mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: example-pvc-volume
    spec:
      storageClassName: hostpath
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  
